# 예외처리
- 프로그램이 실행 도중 오작동을 하거나 비정상적으로 종료되는 경우를 방지하기 위한 처리

## 에러의 종류 3가지
- Compile Error: 프로그램이 시작하기 전 컴파일 할 때 발생하는 에러(가장 좋은 에러...)
- Runtime Error: 프로그램이 작동하는 도중에 발생하는 에러(그나마 나은 에러...)
- Logical Error: 프로그램이 잘 작동하는데 의도와는 다르게 작동하는 에러(답도 없는 에러...)

![Num1](https://drive.google.com/file/d/13DNv9FDUJAeEFrBOquWL2DqtRBxfPfdf/view)
<img src='https://drive.google.com/file/d/13DNv9FDUJAeEFrBOquWL2DqtRBxfPfdf/view' /><br>

![Num2](https://drive.google.com/file/d/1MUoA2nhgOMQZOSKzLxOAQ0VzUlbYSbEe/view?usp=sharing)

- 예외 클래스는 그림과 같이 Runtime Exception과 나머지 Exception으로 분리하여 숙지하면 좋다.
Runtime Exception의 경우 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들이며, 자바의 기본적인 용도에 오류가 있을 때 주로 발생한다. ex) 배열의 범위 초과(ArrayIndexOutOfBoundsException)

- 다른 Exception 클래스는 주로 외부의 영향으로 발생할 수 있는 것들로 프로그램의 사용자들의 동작에 의해 발생하는 경우가 많다. ex) 존재하지 않는 파일 검색(FileNotFoundException)
<br/>
<br/>

## 이러한 Exception을 프로그래머는 코드를 작성하면서 방지해야 한다.
### 이를 예외처리(Exception handling)이라고 한다.
<br/>

결국 예외처리는 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것이다.
만약, 발생한 예외를 처리하지 못하면 프로그램은 비장성적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기'가 받아 원인을 출력한다.

보통 예외처리를 위해서는 try-catch문을 사용한다.
<pre><code>
try{
    //예외가 발생할 가능성 있는 문장
} catch(Exception e1) {
    ...
} catch(Exception e2) {
    ...
} ...
</code></pre>

하나의 try-catch 블럭에는 여러개의 catch가 올 수 있으며, 그 중 일치하는 catch를 찾아 수행하게 된다.

또한, 위와 같이 같은 단계의 catch는 참조변수를 공유하여 사용할 수 있으나, catch 안에 try-catch가 존재하는 경우 다른 참조변수를 사용해야 한다. <br/>
<br/>

## try-catch문의 흐름

try-catch문은 다음과 같이 작동한다.
<br/>
<br/>

try 블럭 내에서 Exception 발생한 경우
  - 발생한 예외와 일치하는 catch 블럭이 있는지 확인한다.
  - 일치하는 catch 블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가 그 다음 문장을 ㅇ행한다.

try 블랙 내에서 Exception 발생하지 않은 경우
  - catch 블럭을 거치지 않고 전체 try-catch문을 빠져나가서 계속 수행

<pre><code>
class Exception{
    public static void main(String args[]) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4);
        } catch (ArithmeticException ae) {
            System.out.println(5);
        }
        System.out.println(6);
    }
}

//Result
1
2
3
5
6
</code></pre>

## 예외의 발생과 catch 블럭

만약 예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어 진다.<br/>
이때, 예외 처리를 위해서는 발생한 예외와 같은 클래스의 인스턴스가 필요한데 모든 예외는 Exception 클래스의 자손이므로 catch 블럭에 exception 클래스를 선언하면 모든 오류를 처리할 수 있다.

<pre><code>
class Exception{
    public static void main(String args[]) {
        System.out.println(1);
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4);
        } catch (ArithmeticException ae) {
            if (ae instanceof ArithmeticException)
                System.out.println("true");
            System.out.println("ArithmeticException");
        } catch (Exception e) {
            System.out.println("Exception")
        }
        System.out.println(6);
    }
}

//Result
1
2
3
true
ArithmeticException
6
</code></pre>

## printStackTrace() 와 getMessage()
<br/>

- printStackTrace() -> 예외 발생 당시의 호출 스택에 있던 메서드의 정보와 예외 메세지 화면에 출력
- getMessage() -> 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻을 수 있다.

  ex) ae.printStackTrace() -> java.lang.ArithmeticException; / ~~~ (Exception.java:7)

<br/>
<br/>

## 멀티 catch 블럭

JDK 1.7부터는 하나의 catch 블럭에 여러개의 오류 선언 가능.
<pre><code>
try{
    ...
}catch (ExceptionA | Exception B){
    e.printStackTrace();
}
</code></pre>

- 하나의 catch블럭으로 여러 예외를 처리하는 것이기에 실제 어떠한 오류가 발생했는지 알 수 없음.
- 참조변수에서 바로 메서드를 호출하여 처리하는 것도 불가능.

- 꼭 필요하다면 if-else 문을 통하여 개별적으로 처리해야 함.
<pre><code>
catch (ExceptionA | Exception B){
    e.methodA(); //에러!

    if(e instanceof ExceptionA) {
        ExceptionA el = (ExceptionA)e;
        el.methodA(); // 가능
    }else {
        ...
    }
    ...
}
</code></pre>
